# Generated by Django 6.0.2 on 2026-02-17 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='flat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='management.property'),
        ),
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ManyToManyField(related_name='leases', to=settings.AUTH_USER_MODEL),
        ),
    ]
