# Generated by Django 6.0.2 on 2026-02-19 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='management.property')),
            ],
        ),
    ]
