# Generated by Django 6.0.2 on 2026-02-19 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_meter_flat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('electricity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('water', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('heat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('utilities_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='management.property')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Meter',
        ),
    ]
