# Generated by Django 6.0.2 on 2026-02-19 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_bill_delete_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('water', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('heat', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('utilities_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='management.lease')),
                ('meters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='management.metersmodel', verbose_name='meters')),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
