# Generated by Django 6.0.2 on 2026-02-20 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_metersmodel_billmodel_delete_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billmodel',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='management.lease'),
        ),
    ]
