# Generated by Django 6.0.2 on 2026-02-20 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_billmodel_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billmodel',
            name='meters',
        ),
        migrations.AddField(
            model_name='metersmodel',
            name='bill',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='management.billmodel'),
        ),
    ]
