# Generated by Django 6.0.2 on 2026-02-21 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_billmodel_meters_metersmodel_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='management.lease'),
        ),
        migrations.AlterField(
            model_name='metersmodel',
            name='bill',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='management.billmodel'),
        ),
    ]
